#!/usr/bin/env bash
# setup-vps script for <host>. Generated by the setup-vps skill; see docs/vps/<host>.md.
# Run one step at a time as root:
#   ssh root@<host> 'bash -s -- <step>' < setup.sh
# Every step is idempotent. Passwords are NOT in this file (they go through chpasswd over stdin).
set -euo pipefail

# ---- facts (filled in from facts.md) ----------------------------------------
ADMIN_GROUP="wheel"          # wheel (RHEL family, Arch) | sudo (Debian, Ubuntu)
SSH_PORT="22"                # from `sshd -T` and `ss -tlnp`, never assumed
FIREWALL="firewalld"         # firewalld | ufw
SELINUX="enforcing"          # enforcing | permissive | disabled | none

# ---- requirements (filled in from the user's answers) -------------------------
# "user:sudo(yes|no):groups(comma-separated)"
USERS=(
  "alice:yes:deploy,shared"
  "bob:no:shared"
)
# "user|public key" (one line per key; public keys are safe to embed)
KEYS=(
  "alice|ssh-ed25519 AAAA... alice@laptop"
)
# "dir:group"
SHARED_DIRS=(
  "/srv:deploy"
  "/shared:shared"
)
WANT_TRAEFIK="yes"
ACME_EMAIL="you@example.com"

# ---- helpers ---------------------------------------------------------------------
log() { printf '\n==> %s\n' "$*"; }
as_deploy() {
  local uid; uid=$(id -u deploy)
  (cd / && runuser -u deploy -- env XDG_RUNTIME_DIR="/run/user/$uid" \
    DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/$uid/bus" "$@")
}

# ---- steps (fill each one in from references/steps.md, adapted to the facts) --------
step_preflight()     { log preflight;     [ "$(id -u)" = 0 ] || { echo "must run as root"; exit 1; }; . /etc/os-release; echo "$PRETTY_NAME"; }
step_packages()      { log packages;      : ; }
step_deploy_user()   { log deploy_user;   : ; }
step_users()         { log users;         : ; }
step_keys()          { log keys;          : ; }
step_shared_dirs()   { log shared_dirs;   : ; }
step_firewall()      { log firewall;      : ; }
step_fail2ban()      { log fail2ban;      : ; }
step_podman_deploy() { log podman_deploy; : ; }
step_traefik()       { log traefik;       [ "$WANT_TRAEFIK" = yes ] || { echo "skipped (not wanted)"; return; }; : ; }
step_verify()        { log verify;        : ; }
step_ssh_harden()    { log ssh_harden;    : ; }

STEPS=(preflight packages deploy_user users keys shared_dirs firewall fail2ban podman_deploy traefik verify ssh_harden)

case "${1:-}" in
  ""|list) printf '%s\n' "${STEPS[@]}" ;;
  *)
    if [[ " ${STEPS[*]} " == *" $1 "* ]]; then "step_$1"; else echo "unknown step: $1" >&2; exit 2; fi
    ;;
esac
